### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by campbe13** [GoogleCloudPlatform/nodejs-getting-started#135] opened 2017-11-29 15:57 UTC
Instructions in readme for 2-structured-data say to copy config-default.json but file does not exist

```
# add your own config information
{
  "GCLOUD_PROJECT": "[YOUR_PROJECT_ID]",
  "DATA_BACKEND": "[cloudsql or mongodb]",
  "MYSQL_USER": "[YOUR_MYSQL_USERNAME]",
  "MYSQL_PASSWORD": "[YOUR_MYSQL_PASSWORD]",
  "INSTANCE_CONNECTION_NAME": "[YOUR_INSTANCE_CONNECTION_NAME]"
}
```

**Comment by ace-n** [comment] 2017-12-20 00:08
Hi @campbe13,

This issue seems like a duplicate of #110, so I'm closing it for now. Please reopen if that's not the case.

Thanks!

**Closed by ace-n** 2017-12-20 00:08 UTC

**Comment by campbe13** [comment] 2017-12-21 02:20
@ace-n should I fork + add the file + PR?  Or leave it?
