### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by khale94** [GoogleCloudPlatform/nodejs-getting-started#177] opened 2018-09-30 02:45 UTC
I'm using node version 8.12.0, npm version 6.4.1. I cloned the project and tried to setup the 1-hello-world app following the instructions in the readme file. When I tried to run 'npm install' I get this error:

  npm ERR! code Z_BUF_ERROR
  npm ERR! errno -5
  npm ERR! zlib: unexpected end of file

Running 'npm install' again will sometimes give this error instead:

  npm ERR! Unexpected end of JSON input while parsing near '...-ie11":"^1.0.0","esli'

Could this be because of my nodejs installing incorrectly? I re-installed it again and still get the same problem. Any help would be appreciated!

**Comment by fhinkel** [comment] 2018-10-04 17:10
@khale94 thanks for raising the issue. I can't reproduce it with Node 8 (or another version). Were you able to resolve it?

**Comment by fhinkel** [comment] 2018-10-08 20:31
Closing this for now. Please let me know if it should be reopened.

**Closed** 2018-10-08 20:31 UTC
