### ISSUE TITLE
ERROR: (gcloud.app.deploy) Error Response: [13] An internal error occurred.

### ISSUE THREAD

**Issue by dfischer** [GoogleCloudPlatform/nodejs-getting-started#172] opened 2018-07-31 02:54 UTC
New project and it's not deploying. 

```
Do you want to continue (Y/n)?  y

Beginning deployment of service [default]...
╔════════════════════════════════════════════════════════════╗
╠═ Uploading 0 files to Google Cloud Storage                ═╣
╚════════════════════════════════════════════════════════════╝
File upload done.
Updating service [default]...failed.
ERROR: (gcloud.app.deploy) Error Response: [13] An internal error occurred.
```

From searching I've tried ` gcloud config set app/use_deprecated_preparation True` which does nothing

**Comment by vlapo** [comment] 2018-07-31 13:07
I had same problem with standard app engine. I try deploy flexible app engine first and it deploy with success. After that I try standard again and it works now.

But still on new project standard app engine deploy dont work.

**Comment by esistgut** [comment] 2018-07-31 13:54
This is happening when trying to deploy the quickstart tutorial too https://cloud.google.com/appengine/docs/standard/nodejs/quickstart

**Comment by steren** [comment] 2018-07-31 15:11
Thanks for the report.

Please let us know:

1. Do you have billing enabled for your project?

2. Are you a project owner in your project?

3. In which region are you deploying?

4. what is your Cloud SDK version? (Please do `gcloud -v`)

**Comment by esistgut** [comment] 2018-07-31 15:19
1. Yes.
2. Yes (and I tested with a project which is not owned to me too).
3. Tested on europe-west1 and another us region which I don't remember, maybe east1.
4. 
```
$ gcloud -v
Google Cloud SDK 209.0.0
alpha 2018.07.16
beta 2018.07.16
bq 2.0.34
core 2018.07.16
gsutil 4.33
```

**Comment by dfischer** [comment] 2018-07-31 15:48
1. Yes
2. Yes
3. central-1 (I believe, that's where everything else has gone. How can I verify?)
4. 

```
gcloud -v
Google Cloud SDK 209.0.0
bq 2.0.34
core 2018.07.16
gsutil 4.33
```

**Comment by steren** [comment] 2018-07-31 15:48
Thanks a lot, we can reproduce (it occurs with newly created projects) and are investigating the issue.

**Comment by squee1945** [comment] 2018-07-31 21:55
This issue should be fixed now. We apologize for any inconvenience and will make adjustments to avoid this problem in the future.

**Closed** 2018-07-31 22:18 UTC

**Comment by dfischer** [comment] 2018-08-01 00:16
Hmm, I'm still getting it:

```
Beginning deployment of service [default]...
#============================================================#
#= Uploading 1 file to Google Cloud Storage                 =#
#============================================================#
File upload done.
Updating service [default]...
.......failed.
ERROR: (gcloud.app.deploy) Error Response: [13] An internal error occurred.
```

**Comment by steren** [comment] 2018-08-01 15:09
Hi @dfischer 

If you can still reproduce, you might be hitting another issue.
Can you share your project ID privately steren@google.com? We'll be investigating.

**Comment by dfischer** [comment] 2018-08-01 23:32
Sent email, thanks.

**Comment by Mark-McCracken** [comment] 2018-08-02 10:09
I have also been facing the exact same issue, cannot deploy to either standard or flex environments.
Running from CentOS, here's my versions:
```bash
gcloud -v
Google Cloud SDK 210.0.0
bq 2.0.34
core 2018.07.27
gsutil 4.33
```
Running with --verbosity=debug, shows some errors at the end, but nothing useful before, looks like my app.yaml is fine, but at the end I've got
```bash
Updating service [default]...failed.                                                                                                                                                                               
DEBUG: (gcloud.app.deploy) Error Response: [13] An internal error occurred.
Traceback (most recent call last):
  File "/var/go/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 848, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/var/go/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 770, in Run
    resources = command_instance.Run(args)
  File "/var/go/google-cloud-sdk/lib/surface/app/deploy.py", line 90, in Run
    parallel_build=False)
  File "/var/go/google-cloud-sdk/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 598, in RunDeploy
    flex_image_build_option=flex_image_build_option)
  File "/var/go/google-cloud-sdk/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 407, in Deploy
    extra_config_settings)
  File "/var/go/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/appengine_api_client.py", line 206, in DeployService
    poller=done_poller)
  File "/var/go/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/operations_util.py", line 315, in WaitForOperation
    sleep_ms=retry_interval)
  File "/var/go/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/waiter.py", line 254, in WaitFor
    sleep_ms, _StatusUpdate)
  File "/var/go/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/waiter.py", line 316, in PollUntilDone
    sleep_ms=sleep_ms)
  File "/var/go/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 229, in RetryOnResult
    if not should_retry(result, state):
  File "/var/go/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/waiter.py", line 310, in _IsNotDone
    return not poller.IsDone(operation)
  File "/var/go/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/operations_util.py", line 184, in IsDone
    encoding.MessageToPyValue(operation.error)))
OperationError: Error Response: [13] An internal error occurred.
ERROR: (gcloud.app.deploy) Error Response: [13] An internal error occurred.
```

Would really appreciate some help with this, don't know how to proceed otherwise, as I've searched through all other similar GitHub issues.

**Comment by steren** [comment] 2018-08-02 14:20
We had a regression in our error message.

Please make sure that your project has a billing account.
If deployment still fail, try enabling the [Cloud Build API](http://console.cloud.google.com/apis/api/cloudbuild.googleapis.com/overview) manually.

As per private conversation, it seems that @dfischer is using a service account to deploy, which might not have the appropriate permissions.

@Mark-McCracken can you tell us more about how you are performing this deployment? Do you have a billing account? What permission does the user or the service account have?

**Comment by Mark-McCracken** [comment] 2018-08-02 15:23
Hi, I've managed to resolve my issue thanks to your comment about Cloud Build API.
I do have a billing account.
I was using a service account, which previously had the following permissions:
```bash
App Engine Admin
App Engine Viewer
App Engine Code Viewer
App Engine Deployer
App Engine Service Admin
Storage Admin
Storage Object Creator
Storage Object Viewer
```

Using the cloud console in the IAM section I added some more permissions for container builder so that it now has the following:
```bash
App Engine Admin
App Engine Viewer
App Engine Code Viewer
App Engine Deployer
App Engine Service Admin
Cloud Build Service Account
Cloud Build Editor
Cloud Build Viewer
Storage Admin
Storage Object Creator
Storage Object Viewer
```

**Comment by fabianschyrer** [comment] 2018-08-17 06:15
Hi everyone, 
I have the same issue, when provisioning a cloud function from the python-sample-docs/functions/gcs

gcloud -v
Google Cloud SDK 212.0.0
beta 2018.07.16
bq 2.0.34
core 2018.08.13
gsutil 4.33

used command:
gcloud beta functions deploy hello_gcs_generic --runtime python37 --verbosity debug --trigger-resource <MY-BUCKET> --trigger-event google.storage.object.finalize

Debug Log:
DEBUG: Running [gcloud.beta.functions.deploy] with arguments: [--runtime: "python37", --trigger-event: "google.storage.object.finalize", --trigger-resource: "<MY-BUCKET>", --verbosity: "debug", NAME: "hello_gcs_generic"]
INFO: Not using a .gcloudignore file.
INFO: Not using a .gcloudignore file.
Deploying function (may take a while - up to 2 minutes)...failed.                                                                                                                                           
DEBUG: (gcloud.beta.functions.deploy) OperationError: code=13, message=Error in the build environment
Traceback (most recent call last):
  File "/Users/<ABC123>/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 848, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/<ABC123>/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 770, in Run
    resources = command_instance.Run(args)
  File "/Users/<ABC123>/google-cloud-sdk/lib/surface/functions/deploy.py", line 196, in Run
    enable_env_vars=True)
  File "/Users/<ABC123>/google-cloud-sdk/lib/surface/functions/deploy.py", line 148, in _Run
    function_ref.Parent().RelativeName())
  File "/Users/<ABC123>/google-cloud-sdk/lib/googlecloudsdk/api_lib/functions/util.py", line 308, in CatchHTTPErrorRaiseHTTPExceptionFn
    return func(*args, **kwargs)
  File "/Users/<ABC123>/google-cloud-sdk/lib/googlecloudsdk/api_lib/functions/util.py", line 375, in CreateFunction
    operations.Wait(op, messages, client, _DEPLOY_WAIT_NOTICE)
  File "/Users/<ABC123>/google-cloud-sdk/lib/googlecloudsdk/api_lib/functions/operations.py", line 126, in Wait
    _WaitForOperation(client, request, notice)
  File "/Users/<ABC123>/google-cloud-sdk/lib/googlecloudsdk/api_lib/functions/operations.py", line 101, in _WaitForOperation
    sleep_ms=SLEEP_MS)
  File "/Users/<ABC123>/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 219, in RetryOnResult
    result = func(*args, **kwargs)
  File "/Users/<ABC123>/google-cloud-sdk/lib/googlecloudsdk/api_lib/functions/operations.py", line 65, in _GetOperationStatus
    raise exceptions.FunctionsError(OperationErrorToString(op.error))
FunctionsError: OperationError: code=13, message=Error in the build environment
ERROR: (gcloud.beta.functions.deploy) OperationError: code=13, message=Error in the build environment

We have other functions running in this project. (Node.js 6 / Provisioned through WUI console)
The project has a proper billing account.
Cloud Build API is enabled

I am using MacOS 10.13.6
Python 2.7, 3.6 and 3.7
using Python 3.7 in virtual environment
virtualenv --python python3 env
source env/bin/activate
pip install google-cloud-storage

So, seems to me like the issue is not only related to AppEngine.
Any advice on this please?
Anything more you need from my side?

Thanks in advance for your help.

**Comment by rickbeacham** [comment] 2018-10-05 23:47
It would be great if gcloud deploy would tell us what might be the reason for not being able to deploy.   
Three main reasons:  Account Permissions, gcloud components, or invalid file types(.DS_Store or Mac Icons).

**Comment by lamotik** [comment] 2018-10-07 17:42
Hi guys, 
I have the same error.

1. gcloud versionGoogle Cloud SDK 219.0.1
beta 2018.07.16
bq 2.0.34
core 2018.09.28
gsutil 4.34

**Comment by melaniedesignreactor** [comment] 2018-11-27 07:05
Hi everyone,

I'm having the same issue here. The deploy was working on Nov 13th.
And it stop working today for only one line of code changes.

I would really like to see if there's a way we can know what is the reason. This is very frustrating.

**Comment by alexanderGalushka** [comment] 2018-11-27 20:09
Same issue. Indeed, very frustrating. Why there is still no proper error reporting? Why there is no deploy config validation tool? Appengine is a great concept but from ops perspective seems poorly implemented.
