### ISSUE TITLE
Doesn't appear to work with yarn

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/nodejs-getting-started#98] opened 2017-02-07 05:54 UTC
Trying to use yarn in 3-binary-data.  Installed deps with `yarn`, and then ran `gcloud app deploy`:

```
beckwith-macbookpro:3-binary-data beckwith$ gcloud app deploy -q
You are about to deploy the following services:
 - compute-summit/default/20170206t215346 (from [/Users/beckwith/Code/nodejs-getting-started/3-binary-data/app.yaml])
     Deploying to URL: [https://compute-summit.appspot.com]

If this is your first deployment, this may take a while...done.                                                                                                             

Beginning deployment of service [default]...
WARNING: Deployment of App Engine Flexible Environment apps is currently in Beta
Building and pushing image for service [default]
WARNING: detect: error Integrity hashes don't match, expected "6fcb8103d6dcaf68cfac1827c88f8535c358fb2fac565f2af79cfeb04633bb57" but got "9979ecaf94f39fc1bff9c7fac76106080de4d3adbc60c558bd305e96ea50dae8"
WARNING: detect: error Found 1 errors.
ERROR: Yarn checker: "yarn.lock" was found indicating Yarn is being used, but "yarn check" indicates "yarn.lock" is invalid.
ERROR: (gcloud.app.deploy) Your application does not satisfy all of the requirements for a runtime of type [nodejs].  Please correct the errors and try again.
beckwith-macbookpro:3-binary-data beckwith$ yarn check
yarn check v0.19.1
error "jade#uglify-js@^2.4.19" doesn't satisfy found match of "uglify-js@2.2.5"
warning "\u001b[2mmysql#\u001b[22mreadable-stream#inherits@~2.0.1" could be deduped from "2.0.3" to "inherits@2.0.3"
warning "mongodb#readable-stream#inherits@~2.0.1" could be deduped from "2.0.3" to "inherits@2.0.3"
warning "duplexify#readable-stream#inherits@~2.0.1" could be deduped from "2.0.3" to "inherits@2.0.3"
warning "through2#readable-stream#inherits@~2.0.1" could be deduped from "2.0.3" to "inherits@2.0.3"
warning "concat-stream#readable-stream#inherits@~2.0.1" could be deduped from "2.0.3" to "inherits@2.0.3"
warning "superagent#readable-stream#inherits@~2.0.1" could be deduped from "2.0.3" to "inherits@2.0.3"
warning "base64url#concat-stream#inherits@~2.0.1" could be deduped from "2.0.3" to "inherits@2.0.3"
warning "bl#readable-stream#inherits@~2.0.1" could be deduped from "2.0.3" to "inherits@2.0.3"
info Found 8 warnings.
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

**Comment by DominicKramer** [comment] 2017-02-07 18:31
I've been able to reproduce the error you encountered.

Both `npm` version 3.10.10 and `yarn` version 0.19.1 install `jade` version 1.11.0, which needs `uglify-js` version `^2.4.19`.  However, `npm install` correctly installs `uglify-js` 2.7.5 that satisfies the requirement for `jade`, but `yarn install` only installs `uglify-js` 2.2.5 that doesn't satsify `^2.4.19`.  Based on this, it looks like this could be a bug in `yarn` itself.

**Comment by jmdobry** [comment] 2017-02-07 18:34
I'm going to see if I can fix this in the repo, but the tutorial has been updated to include instructions about Yarn, including deleting the `yarn.lock` to cause deployment to fall back to `npm install`.

**Comment by DominicKramer** [comment] 2017-02-15 22:20
The newest release of Google Cloud SDK (version 144.0.0) addresses this issue.  I have confirmed that the `3-binary-data` example can be deployed with `yarn` and deploys with `npm` if `yarn.lock` is specified in the `skip_files` section of `app.yaml`.

**Comment by ace-n** [comment] 2017-08-07 22:10
Closing this issue as it seems to be resolved. @JustinBeckwith feel free to reopen if this is not the case. Thanks!

**Closed by ace-n** 2017-08-07 22:10 UTC
